Bug: only call `dict()` if required.
mozilla-services/contile-integration-tests pull request #147
Opened 2022-01-27 00:10 UTC by jrconlin

Not sure why, but in `test_contile.py`, `step.response.content` (line 44) is already a `dict` in a number of cases (See [failed build](https://app.circleci.com/pipelines/github/mozilla-services/contile/704/workflows/ef078292-d86f-4cd4-be33-6155313138ba/jobs/2668). I added a hack to check the instance type and only call `dict()` if required.

2022-01-27 00:38 UTC, pjenvey requested changes
It's [typed to be json or Any](https://github.com/mozilla-services/contile-integration-tests/blob/1faaeb25dc071a21eecc4fcadf67f4cfd41981bc/client/tests/models.py#L48) (likely just a string) so lgtm

2022-01-27 00:51 UTC, pjenvey approved these changes
er meant to approve that

2022-01-27 15:56 UTC, jrconlin commented
The issue is https://github.com/mozilla-services/contile/issues/347, which is causing https://github.com/mozilla-services/contile/pull/346 to block (my apologies for not including these in the summary). 

And yes, you're correct. I didn't understand the role of the Model here so I was simply reacting to the generated JSON output. Removing the `position` field from the model should resolve the problem. I will adjust the PR.

2022-01-27 16:37 UTC, hackebrot commented
My recommendation would be to error when loading the scenarios from file.

If there's a response with a status code of `200 OK` but not a valid response content, we should abort the test run. As that would be a test setup error rather than an actual test failure.

If you don't mind I'll push commits for this to your branch, @jrconlin.

2022-01-27 17:08 UTC, jrconlin commented
Please! You know the tool better than I do.

2022-01-27 17:53 UTC, hackebrot commented
I have decided to create #150 for the improve error reporting as opposed to reverting the changes to `client/tests/test_contile.py`.

Please review #150, once that's merged we can rebase this branch and have it only delete the `position` field on the model and improve the path handling in `partner/config/gunicorn_conf.py`.

2022-01-27 23:51 UTC, jrconlin commented
Closing in favor of #150

2022-01-28 00:35 UTC, pjenvey approved these changes
just needs a cleanup of the commit message when squashing

2022-01-28 10:16 UTC, hackebrot approved these changes
LGTM! 🚀

2022-01-28 10:51 UTC, merged