Example test for tiles dont pass the filter
mozilla-services/contile-integration-tests pull request #66
Opened 2021-08-20 20:28 UTC by ashrivastava-qa

**This is not a working test.** 
It is just to document how to write an example test for Tiles that don't pass the filter.
Added test `success_tablet_android_return_tiles_that_pass_filter` in `scenarios.yml` file that contains `user-agent` as `form-factor: tablet` and `os-family: andoid` and `country-code: US` and `region code: WA` to demonstrate the use of geo-location as well for this example test. 
In the `response.yml` file I added a response from` tablet: android` having the second response that doesn't conform to the filter specification and hence for this test only the first filter should be returned.

2021-08-20 20:32 UTC, jrconlin commented
Heh, I was wondering how you'd test a negative in this situation.

2021-08-25 08:30 UTC, hackebrot requested changes
Hi @ashrivastava-qa! 👋🏻 

We need to make sure that this context is documented in the test scenario, so folks are not confused when this new test doesn’t work. It would also be good to mention why the test expects only a single tile (`Example NET` is no a recognized provider in `adm_settings.json`).

Currently `woothee` resolves `’Mozilla/5.0 (Android; Tablet; rv:40.0) Gecko/40.0 Firefox/40.0’` to `{'name': 'Firefox', 'category': 'smartphone', 'os': 'Android', 'os_version': 'UNKNOWN', 'version': '40.0', 'vendor': 'Mozilla'}`, however the scenario comment doesn’t reflect that.

We include `country-code` and `region-code` in the URLs in the responses if they are only returned for a specific country and region. The new response would be returned for any request from an android tablet device. I recommend either updating the URLs in the response or moving it to a new file at `volumes/partner/US/WA.yml`

I would also mention that IP lookups in Contile require a MaxMind DB. When running these tests locally one would need to mount that file to the Contile Docker container and set the according environment variable too (See https://github.com/mozilla-services/contile/blob/274f708bbbe8f2bf0af1bb045a8870dc34b53d65/docker-compose.yml#L25-L41).

2021-08-31 14:52 UTC, ashrivastava-qa commented
Hi @hackebrot I made the changes you requested. I tried documenting the scenario as much as I could but please let me know if I missed anything else. Also I removed the whole geolocation step to make this example test simpler.

2021-09-01 08:41 UTC, hackebrot requested changes
Hi @ashrivastava-qa! 👋🏻 

I've added my comments with suggested changes inline.

2021-09-01 08:41 UTC, hackebrot commented on volumes/client/scenarios.yml
> +          status_code: 200
Please move the above comment about the `status_code` code here and refer to the name of the scenario, so it's easier to find: `error_phone_android_reqwest_error`.

2021-09-01 08:41 UTC, hackebrot commented on volumes/client/scenarios.yml
> +            # The response below returned only 1 tile because the other tile (.NET) didn't pass the filter specification in the adm_settings.json
```suggestion
            # We expect only 1 tile because 'Example NET' is not an expected advertiser (per adm_settings.json) 
```

2021-09-01 08:41 UTC, hackebrot commented on volumes/partner/responses.yml
> +            advertiser_url: 'https://www.example.net/desktop_android'
Please add a newline at the end of the file.

2021-09-01 08:41 UTC, hackebrot commented on volumes/partner/responses.yml
> +            name: 'Example NET' # this tile doesn't conforms to the filter specs (.NET is not an acceptable host in adm_settings.json)
```suggestion
            name: 'Example NET' # this tile is from an unexpected advertiser (per adm_settings.json)
```

2021-09-01 08:41 UTC, hackebrot commented on volumes/partner/responses.yml
> +            click_url: 'https://example.com/desktop_android?version=16.0.0&key=22.1&ci=6.2&ctag=1612376952400200000'
Please update all URLs for this response to contain the correct `form-factor`:

```suggestion
            click_url: 'https://example.com/tablet_android?version=16.0.0&key=22.1&ci=6.2&ctag=1612376952400200000'
```

2021-09-02 07:58 UTC, hackebrot approved these changes
Thank you @ashrivastava-qa! LGTM. 📦

2021-09-02 07:58 UTC, merged